LLVM 8 release
IITH-Compilers/IR2Vec pull request #4
Opened 2021-02-09 19:17 UTC by rohitaggarwal007

2021-02-09 20:01 UTC, svkeerthy commented on src/test-suite/sanity_check.sh.cmake
>  SEED_VERSION=$2
Shall we remove $2 altogether?

2021-02-10 17:49 UTC, svkeerthy requested changes
sanity_check.sh.cmake needs fixing as discussed

2021-02-10 18:36 UTC, rohitaggarwal007 commented on src/test-suite/sanity_check.sh.cmake
>  SEED_VERSION=$2
Remove the if clause for SEED_VERSION

2021-02-10 18:40 UTC, rohitaggarwal007 commented
> sanity_check.sh.cmake needs fixing as discussed

Done

2021-02-10 18:44 UTC, svkeerthy approved these changes

2021-02-10 18:46 UTC, merged