On demand
IITH-Compilers/IR2Vec pull request #63
Opened 2023-02-12 15:46 UTC by PrasannaLanka

2023-02-13 03:33 UTC, ShikharJain97 commented on src/libIR2Vec.cpp
> +  } else if (mode == IR2Vec::IR2VecMode::Symbolic && !fname.empty()) {
suppose user doesnt gave any function name and want symbolic embeddings, will this work?

2023-02-13 03:38 UTC, ShikharJain97 reviewed
code seems to be correct for on demand symbolic encoding generation.

2023-03-26 10:25 UTC, svkeerthy requested changes

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +      Function *foo = const_cast<Function *>(calledFunction);
Use auto, give better variable name and change const_cast.

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +  visitedFunctions.insert(function);
Please add an assertion on function for nullptr

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +    std::unordered_set<const llvm::Function *> &visitedFunctions) {
Can we make the argument as const?

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +  collectWriteDefsMap(M);
Can this also be moved to constructor and removed from `generateFlowAwareEncodings()` as well?

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +      std::unordered_set<const Function *> visitedFunctions;
Please change this to appropriate LLVM set container

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +    char *const readable_name =
Please create a function to get demangled method name and call it in both the places.

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +    char *const readable_name =
Also appropriately change the existing logic in `generateFlowAwareEncodings()` to make the call to the same function.

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +  for (auto &f : M) {
This logic is very similar to what we have in `generateFlowAwareEncodings()`. Please try creating a function and use it in both the places.

2023-03-26 10:25 UTC, svkeerthy commented on src/FlowAware.cpp
> +  for (auto &f : M) {
This logic is very similar to what we have in `generateFlowAwareEncodings()`. Please try creating a function and use it in both the places.

2023-03-26 10:25 UTC, svkeerthy commented on src/IR2Vec.cpp
> +cl::opt<std::string> cl_fname("fname", cl::Optional, cl::init(""),
fname could be perceived as file name as well. Please consider renaming it appropriately.

2023-03-26 10:25 UTC, svkeerthy commented on src/IR2Vec.cpp
> +  // newly added
Seems like the file descriptors are not closed even in the existing code. Can you please close them appropriately?

2023-03-31 11:43 UTC, svkeerthy approved these changes

2023-03-31 12:02 UTC, merged