Llvm17lit
IITH-Compilers/IR2Vec pull request #95
Opened 2024-02-16 16:01 UTC by nishant-sachdeva

- Adding LIT based integration testing to replace `make verify-all` based testing

2024-04-21 08:30 UTC, svkeerthy requested changes

2024-04-21 08:30 UTC, svkeerthy commented on docs/spec_compilation.md
> +- Create config file, using `config_clang14_cpu2006.cfg`. Change compilation parameters to appropriate llvm version.
Can you please list the parameters as well..

2024-04-21 08:30 UTC, svkeerthy commented on docs/spec_compilation.md
> +- Once the `.o` files are generated, run the script (`get_ll_spec.sh`) with appropriate changes to get these files together in the repo.
where is get_ll_spec.sh? Please add the link.

2024-04-21 08:30 UTC, svkeerthy commented on docs/spec_compilation.md
> +- Create config file, using `config_clang14_cpu2017.cfg`. Change compilation parameters to appropriate llvm version.
Similar changes here please.

2024-04-21 08:30 UTC, svkeerthy commented on docs/version_upgrade_process.md
> +The following guide details the steps followed in the upgrade process for IR2Vec.
"The following guide details the steps followed in upgrading the LLVM version supported by IR2Vec"

2024-04-21 08:30 UTC, svkeerthy commented on docs/version_upgrade_process.md
> +   - Our relevant scripts and files will be present in the folder `collect_ir`.
Please make it clear.

2024-04-21 08:30 UTC, svkeerthy commented on docs/version_upgrade_process.md
> +      - For detailed instructions on this step, refer to [here](https://github.com/nishant-sachdeva/IR2Vec/wiki/spec_compilation).
Please fix the link to point to IITH-Compilers/IR2Vec

2024-05-15 04:49 UTC, svkeerthy requested changes

2024-05-15 04:49 UTC, svkeerthy commented on Manylinux2014_Compliant_Source/pkg/build.sh
> +cp vocabulary/seedEmbeddingVocab.txt Manylinux2014_Compliant_Source/pkg/ir2vec/
This vocabulary need not be copied anymore. Please check and remove.

2024-05-15 13:07 UTC, svkeerthy requested changes

2024-05-15 13:07 UTC, svkeerthy commented on Manylinux2014_Compliant_Source/pkg/build.sh
> +s#!/bin/bash
Please fix this.

2024-05-15 16:41 UTC, nishant-sachdeva commented on Manylinux2014_Compliant_Source/pkg/build.sh
> +s#!/bin/bash
Pushed changes for this

2024-05-15 17:03 UTC, merged