created file to generated vocabulary as map
IITH-Compilers/IR2Vec pull request #98
Opened 2024-03-28 10:17 UTC by PrasannaLanka

2024-03-28 10:28 UTC, svkeerthy commented on vocabulary.h
This generated vocabulary need not be checked in. It can be generated in the build folder. You can make appropriate changes in the CMakeLists. Install cases should also be handled.

2024-03-28 10:33 UTC, PrasannaLanka commented on vocabulary.h
Ok I will update.

2024-04-21 10:12 UTC, svkeerthy requested changes
Please change README to remove vocab in the usage and other places. @PrasannaLanka

2024-04-23 07:30 UTC, svkeerthy approved these changes

2024-04-23 07:30 UTC, merged